name: Experiment

on:
  pull_request:
  push:
    branches: [main]

jobs:
  gpu:
    name: CUDA packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: twesterhout
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build
      run: |
        nix build --option max-jobs 1 --option cores 2 --accept-flake-config -L \
          .#cuda.python3Packages.halide .#cuda.python3Packages.cupy .#cuda.python3Packages.cuquantum .#cuda.python3Packages.qsimcirq \
          .#cuda.python311Packages.halide .#cuda.python311Packages.cupy .#cuda.python311Packages.cuquantum .#cuda.python311Packages.qsimcirq
  cpu:
    name: CPU-only packages
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest # x64
          - os: ubuntu-24.04-arm # arm64
          - os: macos-latest # arm64
          - os: macos-13 # x64 
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: twesterhout
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build quspin-extensions (Python 3.12)
      run: |
        nix build --option max-jobs 1 --option cores 1 --accept-flake-config -L .#cpu.python312Packages.quspin-extensions
    - name: Build quspin-extensions (Python 3.11)
      run: |
        nix build --option max-jobs 1 --option cores 1 --accept-flake-config -L .#cpu.python311Packages.quspin-extensions
    - name: Build quspin
      run: |
        nix build --option max-jobs 1 --accept-flake-config -L \
          .#cpu.python3Packages.quspin \
          .#cpu.python311Packages.quspin
    - name: Build qsimcirq
      if: matrix.os == 'ubuntu-latest'
      run: |
        nix build --option max-jobs 1 --accept-flake-config -L \
          .#cpu.python3Packages.qsimcirq \
          .#cpu.python311Packages.qsimcirq
